@SWP_BE_HostAddress = http://localhost:5019

GET {{SWP_BE_HostAddress}}/health
Accept: application/json

###

POST {{SWP_BE_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "student01",
  "email": "student01@example.com",
  "fullName": "Student 01",
  "password": "secret123"
}

###

POST {{SWP_BE_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "student01",
  "password": "secret123"
}

###
